### ISSUE TITLE
Incomplete WMS request: VERSION parameter missing

### ISSUE THREAD

**Issue by stodge** [camptocamp/docker-mapserver#123]
I'm not sure if I'm doing something wrong, but I always get the error:

```
msWMSDispatch(): WMS server error. Incomplete WMS request: VERSION parameter missing
```

My test URL is:

`curl -X GET http://localhost:8888?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=polygons&SRS=EPSG:4326&BBOX=-124,21,-66,49&WIDTH=600&HEIGHT=400&FORMAT=image/png`

The only logging I get from mapserver is:

```
cat /tmp/mapserver_error.log 
[Thu Apr  8 18:40:03 2021].398120 loadParams() QUERY_STRING: SERVICE=WMS
```

I don't know if the cgi wrapper isn't passing on the rest of the query parameters? Or it can't read the map file?

`-rw-r--r--. 1 root root 15277 Apr  8 18:33 mapserver.map`

Thanks

**Comment by sbrunner** [comment]
How do you run the container?

**Comment by stodge** [comment]
Oh, sorry! I'm using docker-compose:

```
  mapserver:
    image: camptocamp/mapserver:7.2
    volumes:
      - ./src/mapserver/mapfile.txt:/etc/mapserver/mapserver.map
      - ./src/mapserver/fonts.list:/etc/mapserver/fonts.list
    ports:
      - "8888:80"
    restart: on-failure
    depends_on:
      - database
    environment:
      - MS_DEBUGLEVEL=5
      - MS_ERRORFILE=/tmp/mapserver_error.log
```
