### ISSUE TITLE
publish mapserver at a path

### ISSUE THREAD

**Issue by pvgenuchten** [camptocamp/docker-mapserver#565]
not sure if this is a mapserver or docker (or misconfiguration) issue, just posting it here to hear your thoughts.

when i deploy mapserver-docker at a path '/ows' using k8s-nginx-ingress, the mapfile key from path is no longer identified. with map config set to:

```
Maps
  "clay" "/srv/data/clay.map"
END
```

and ingress config:

```
      - backend:
          service:
            name: mapserver
            port:
              number: 80
        path: /ows(/|$)(.*)
        pathType: Prefix
```

/ows/clay?request=getcapabilities&service=wms returns "msCGILoadMap(): Web application error. CGI variable "map" is not set."

/ows/clay?request=getcapabilities&service=wms&map=clay works fine though
